services:
  fastapi-app:
    build:
      context: ./transfermarkt-api
      dockerfile: Dockerfile
    container_name: fastapi-dev
    ports:
      - "9000:9000"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
    env_file:
      - ./transfermarkt-api/.env
    volumes:
      - ./transfermarkt-api:/app
    restart: no

  redis:
    image: "redis:7-alpine"
    container_name: redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis-dev-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru

volumes:
  redis-dev-data:
